name: PR Check (open PR for branch)
description: Finds an open PR for a branch; outputs pr_exists, pr_number, pr_url
inputs:
  github-token:
    description: GitHub token with repo scope (use GITHUB_TOKEN)
    required: true
  branch:
    description: Branch to search (defaults to current ref_name)
    required: false
outputs:
  pr_exists:
    description: 'true/false'
    value: ${{ steps.find.outputs.pr_exists }}
  pr_number:
    description: 'PR number (if exists)'
    value: ${{ steps.find.outputs.pr_number }}
  pr_url:
    description: 'PR URL (if exists)'
    value: ${{ steps.find.outputs.pr_url }}
runs:
  using: composite
  steps:
    - id: find
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        BRANCH: ${{ inputs.branch || github.ref_name }}
      run: |
        set -Eeuo pipefail

        # Guard: gh must exist
        if ! command -v gh >/dev/null 2>&1; then
          echo "gh CLI not found; assuming no open PR for branch '$BRANCH'" >&2
          echo "pr_exists=false"  >> "$GITHUB_OUTPUT"
          echo "pr_number="       >> "$GITHUB_OUTPUT"
          echo "pr_url="          >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Guard: jq must exist
        if ! command -v jq >/dev/null 2>&1; then
          echo "jq not found; assuming no open PR for branch '$BRANCH'" >&2
          echo "pr_exists=false"  >> "$GITHUB_OUTPUT"
          echo "pr_number="       >> "$GITHUB_OUTPUT"
          echo "pr_url="          >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Query GH for an open PR on this branch.
        # If gh fails for any reason, fall back to empty JSON array.
        pr_json=$(gh pr list --state open --head "$BRANCH" --json number,url || true)

        pr_number=$(jq -r '.[0].number // empty' <<<"$pr_json")
        pr_url=$(jq -r '.[0].url // empty' <<<"$pr_json")

        if [[ -n "$pr_number" ]]; then
          echo "pr_exists=true"   >> "$GITHUB_OUTPUT"
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
          echo "pr_url=$pr_url"   >> "$GITHUB_OUTPUT"
        else
          echo "pr_exists=false"  >> "$GITHUB_OUTPUT"
          echo "pr_number="       >> "$GITHUB_OUTPUT"
          echo "pr_url="          >> "$GITHUB_OUTPUT"
        fi
