name: PR Check (open PR for branch)
description: Finds an open PR for a branch; outputs pr_exists, pr_number, pr_url
inputs:
  github-token:
    description: GitHub token with repo scope (use GITHUB_TOKEN)
    required: true
  commit-identifier:
    description: Commit SHA to search for
    required: false
outputs:
  pr_exists:
    description: 'true/false'
    value: ${{ steps.find.outputs.pr_exists }}
  pr_number:
    description: 'PR number (if exists)'
    value: ${{ steps.find.outputs.pr_number }}
  pr_url:
    description: 'PR URL (if exists)'
    value: ${{ steps.find.outputs.pr_url }}
runs:
  using: composite
  steps:
    - id: find
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        COMMIT: ${{ inputs.commit-identifier }}
      run: |
        set -Eeuo pipefail

        # Guard: curl and jq must exist
        if ! command -v curl >/dev/null 2>&1; then
          echo "curl not found; assuming no open PR for commit '$COMMIT'" >&2
          echo "pr_exists=false"  >> "$GITHUB_OUTPUT"
          echo "pr_number="       >> "$GITHUB_OUTPUT"
          echo "pr_url="          >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if ! command -v jq >/dev/null 2>&1; then
          echo "jq not found; assuming no open PR for commit '$COMMIT'" >&2
          echo "pr_exists=false"  >> "$GITHUB_OUTPUT"
          echo "pr_number="       >> "$GITHUB_OUTPUT"
          echo "pr_url="          >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Get repo info from GITHUB_REPOSITORY
        REPO_FULL=${GITHUB_REPOSITORY}
        OWNER=$(echo "$REPO_FULL" | cut -d'/' -f1)
        REPO=$(echo "$REPO_FULL" | cut -d'/' -f2)

        # Query GitHub API for PRs containing the commit
        api_url="https://api.github.com/repos/$OWNER/$REPO/commits/$COMMIT/pulls"
        pr_json=$(curl -sSL -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github.groot-preview+json" "$api_url" || true)

        pr_number=$(jq -r '[.[] | select(.state == "open")][0].number // empty' <<<"$pr_json")
        pr_url=$(jq -r '[.[] | select(.state == "open")][0].html_url // empty' <<<"$pr_json")

        if [[ -n "$pr_number" ]]; then
          echo "Found open PR #$pr_number for commit '$COMMIT'"
          echo "pr_exists=true"   >> "$GITHUB_OUTPUT"
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
          echo "pr_url=$pr_url"   >> "$GITHUB_OUTPUT"
        else
          echo "No open PR found for commit '$COMMIT'"
          echo "pr_exists=false"  >> "$GITHUB_OUTPUT"
          echo "pr_number="       >> "$GITHUB_OUTPUT"
          echo "pr_url="          >> "$GITHUB_OUTPUT"
        fi
