name: "Publish Changes"
description: "Publish Changes using Terraform Output"
inputs:
    terraform_root:
      description: "Terraform root configuration name"
      required: true
    terraform_workspace:
      description: "Terraform workspace to select"
      required: true

outputs:
  name_prefix:
    description: "The computed name_prefix"
    value: ${{ steps.set_outputs.outputs.name_prefix }}

runs:
  using: "composite"
  steps:
  - name: Npm CI
    shell: bash
    run: npm ci

  - name: Terraform Deploy
    shell: bash
    working-directory: terraform/${{ inputs.terraform_root }}
    run: |
      echo terraform init
      terraform init -upgrade

      echo select terraform workspace ${{ inputs.terraform_workspace }}
      node ../../node_modules/.bin/core-build select-workspace -w ${{ inputs.terraform_workspace }}

      echo terraform validate
      ../../node_modules/.bin/env-cmd -f ../.env terraform validate -no-color

      echo terraform apply
      ../../node_modules/.bin/env-cmd -f ../.env terraform apply -auto-approve -no-color -input=false

  - name: Set Outputs
    id: set_outputs
    shell: bash
    working-directory: terraform/${{ inputs.terraform_root }}
    run: echo "::set-output name=name_prefix::$(terraform output name_prefix)"
