name: "Increment Version and Create Tag"
description: "Creates a new GitHub tag with an incremented major, minor, patch, or pre-release suffix number.
  Defaults to patch or pre-release, depending on whether it is in the main branch, but can be overridden by commit messages."

inputs:
  github_token:
    description: Auth token for GitHub
    required: true
  package_version:
    description: New NPM package version
    required: true

runs:
  using: "composite"
  steps:
    - name: Bump Package Version
      shell: bash
      run: npm version ${{ inputs.package_version }}
    - name: Publish GitHub Package
      shell: bash
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github_token }}
