name: 'Run Semgrep'
description: 'Run a Semgrep scan and output results for reviewdog and future steps'
outputs:
  normalizedBaseline:
    description: 'The resolved baseline ref used for reviewdog annotations'
    value: ${{ steps.run-semgrep.outputs.normalizedBaseline }}
  scanSummary:
    description: 'Markdown summary of the Semgrep scan results'
    value: ${{ steps.run-semgrep.outputs.scanSummary }}
  configSummary:
    description: 'Markdown summary of the Semgrep configuration used'
    value: ${{ steps.run-semgrep.outputs.configSummary }}
  scanStatus:
    description: 'success/failure based on findings and input fail level'
    value: ${{ steps.run-semgrep.outputs.scanStatus }}
  totalFindings:
    description: 'Total number of findings from the Semgrep scan'
    value: ${{ steps.run-semgrep.outputs.totalFindings }}
  numErrors:
    description: 'Number of findings at error severity level'
    value: ${{ steps.run-semgrep.outputs.numErrors }}
  numWarnings:
    description: 'Number of findings at warning severity level'
    value: ${{ steps.run-semgrep.outputs.numWarnings }}
  numInfos:
    description: 'Number of findings at info severity level'
    value: ${{ steps.run-semgrep.outputs.numInfos }}

runs:
  using: composite
  steps:
    - name: Run Semgrep Scan
      id: run-semgrep
      shell: bash
      run: node ${{ github.action_path }}/run-semgrep.js
