name: Terraform Plan Comment
description: Create a terraform plan comment in the PR
inputs:
  terraform_plan_path:
    description: The path to the file containing the contents of the terraform plan
    required: true
  terraform_environment:
    description: Terraform environment
    required: true

runs:
  using: composite
  steps:
    - name: Download Terraform Plan Artifact
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
        path: /tmp/terraform-plan

    - name: Read Terraform Plan
      id: read_plan
      shell: bash
      run: echo "TERRAFORM_PLAN=$(cat /tmp/terraform-plan/${{ inputs.terraform_plan_path }})" >> $GITHUB_ENV

    - name: Comment on PR
      uses: actions/github-script@v6
      shell: bash
      env:
        PLAN: ${{ env.TERRAFORM_PLAN }}
      with:
        script: |
          const CODE_BLOCK = '```';

          const output = `
          ### Terraform Plan ${{ inputs.terraform_environment }} 🔍
          <details>
          <summary>Logs</summary>

          ${ CODE_BLOCK }terraform
          ${ process.env.PLAN }
          ${ CODE_BLOCK }
          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });
