name: Terraform Plan Comment
description: Create a terraform plan comment in the PR
inputs:
  terraform_plan:
    description: The contents of the terraform plan
    required: true
  terraform_environment:
    description: Terraform environment
    required: true

runs:
  using: composite
  steps:
    - name: Comment on PR
      uses: actions/github-script@v6
      env:
        PLAN: "${{ inputs.terraform_plan }}"
      with:
        script: |
          const CODE_BLOCK = '```';

          const output = `
          ### Terraform Plan ${{ inputs.terraform_environment }} 🔍
          <details>
          <summary>Logs</summary>

          ${ CODE_BLOCK }terraform
          ${ process.env.PLAN }
          ${ CODE_BLOCK }
          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });
