name: "Reusable - Deploy Feature Branch to Dev"

on:
  workflow_call:
    inputs:
      aws_region:
        description: 'AWS region'
        required: true
        type: string
      terraform_root:
        description: 'Terraform root directory'
        required: true
        type: string
      terraform_workspace:
        description: 'Terraform workspace'
        required: true
        type: string
      node_version:
        description: 'Node.js version'
        required: true
        type: string
      role_session_name_suffix:
        description: 'Suffix for the role session name'
        required: true
        type: string
    secrets:
      ORG_READ_ONLY_SSH_KEY:
        required: true
      ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  BuildAndApply:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - id: get-role-arn
        uses: OpenSesame/gha-oidc-access/get-role-arn@v2
        with:
          domain: core
          env: dev
          ORG_READ_ONLY_SSH_KEY: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.get-role-arn.outputs.role-arn }}
          role-session-name: deployBranchDev-Run${{ inputs.role_session_name_suffix }}
          aws-region: ${{ steps.get-role-arn.outputs.region }}

      - name: Actions - Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
          terraform_wrapper: false

      - name: Build And Apply Feature Branch to Dev
        uses: opensesame/core-github-actions/build-apply@v1
        with:
          github_ssh_key: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}
          terraform_root: dev
          terraform_workspace: ${GITHUB_REF##*/}
          node_auth_token: ${{ secrets.ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN }}

      - name: Deploy to Dev
        uses: opensesame/core-github-actions/deploy@v1
        with:
          github_ssh_key: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}
          terraform_root: dev
          terraform_workspace: ${GITHUB_REF##*/}
