name: "IUM Invitation E2E Tests"

on:
  workflow_call:
    inputs:
      terraform_workspace:
        description: 'Terraform workspace'
        required: true
        type: string
      role_session_name_suffix:
        description: 'Suffix for the role session name'
        required: true
        type: string
      deploy_fargate:
        description: 'Deploy Fargate'
        required: true
        default: false
        type: boolean
      slack_notification_title:
        description: 'Slack Notification Title'
        required: false
        type: string
      DEV_ROLE_ARN:
        description: 'Role ARN for Dev'
        required: false
        type: string
      STAGE_ROLE_ARN:
        description: 'Role ARN for Stage'
        required: false
        type: string
    secrets:
      ORG_READ_ONLY_SSH_KEY:
        required: true
      ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN:
        required: true
      CORE_ENG_DEPLOYMENTS_SLACK_WEBHOOK:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  Authorize_Dev:
    name: E2E Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - id: get-role-arn
        uses: OpenSesame/gha-oidc-access/get-role-arn@v2
        with:
          domain: core
          env: dev
          ORG_READ_ONLY_SSH_KEY: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.get-role-arn.outputs.role-arn }}
          role-session-name: deployBranchDev-Run${{ inputs.role_session_name_suffix }}
          aws-region: ${{ steps.get-role-arn.outputs.region }}

      - name: Checkout Actions
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN }}
        run: |
          cd e2e
          npm ci

      - name: Authorize tests in DEV
        run: |
          node e2e/cli/authorize.js --dev
          echo "IUM_ACCESS_TOKEN=$(cat ium.txt)" >> $GITHUB_ENV

  Authorize_Stage:
    name: E2E Stage
    runs-on: ubuntu-latest
    environment: stage
    needs: Authorize_Dev

    steps:
      - id: get-role-arn
        uses: OpenSesame/gha-oidc-access/get-role-arn@v2
        with:
          domain: core
          env: stage
          ORG_READ_ONLY_SSH_KEY: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.get-role-arn.outputs.role-arn }}
          role-session-name: deployBranchStage-Run${{ inputs.role_session_name_suffix }}
          aws-region: ${{ steps.get-role-arn.outputs.region }}

      - name: Checkout Actions
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN }}
        run: |
          cd e2e
          npm ci

      - name: Authorize tests in STAGE
        run: |
          node e2e/cli/authorize.js --stage
          echo "USERSTORE_ACCESS_TOKEN=$(cat ius.txt)" >> $GITHUB_ENV

      - name: Running E2E Tests
        env:
          IUM_ACCESS_TOKEN: ${{ env.IUM_ACCESS_TOKEN }}
          USERSTORE_ACCESS_TOKEN: ${{ env.USERSTORE_ACCESS_TOKEN }}
          TF_API_ENDPOINT: ${{ env.TF_API_ENDPOINT }}
        run: |
          cd e2e
          npm run test

      - uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "E2E Test Status for ${{ github.ref_name }} - <${{ github.workflow_ref }}|Link to Run>"
          message_format: "{emoji} E2E Tests {status_message} in <{repo_url}|{repo}>"
          footer: "Workflow: {run_url}|View>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CORE_ENG_DEPLOYMENTS_SLACK_WEBHOOK }}
