name: Release Management

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  Releasing:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest tag and release
        id: latest
        run: |
          tag=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          echo "tag_name=$tag" >> $GITHUB_OUTPUT

      - name: Delete Current tag and release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest.outputs.tag_name }}

      - name: Create new Git Tag
        uses: tvdias/github-tagger@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.latest.outputs.tag_name }}

      - name: Create new Git Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest.outputs.tag_name }}
          release_name: ${{ steps.latest.outputs.tag_name }}