on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1

      - name: Get current version
        id: version
        shell: bash
        run: |
          version=$(grep version package.json | awk -F \" '{print $4}')
          echo version: $version
          echo ::set-output name=version::$version
