name: SonarQube Scan

on:
  workflow_call:
    inputs:
      commit-identifier:
        description: Commit SHA or ref to scan; defaults to the ref that triggered the workflow
        type: string
        required: false
        default: ''
    secrets:
      SONAR_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  sonar-scan:
    name: Run SonarQube scan
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.commit-identifier }}
          fetch-depth: 0

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@d209202bc7d53ff1cc128f7f907dac145c9d6ae9 # v8.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
