name: TF Validate/Plan ENV Roots

on:
  workflow_call:
    inputs:
      commit-identifier:
        description: SHA or tag for terraform validate and plan, (optional) when omitted, the head of the selected branch is used
        type: string
        required: false
      oidc_domain:
        description: 'OIDC Domain. Defaults to "core" when omitted'
        required: false
        type: string
        default: 'core'
      terraform-workspace:
        description: Terraform Workspace, (optional) when omitted, the environment is used
        type: string
        required: false
      terraform-version:
        description: Terraform version to use
        type: string
        required: true
      terraform-root-dev:
        description: Root directory of terraform dev. When omitted, terraform/dev is used
        type: string
        required: false
      terraform-root-stage:
        description: Root directory of terraform stage. When omitted, terraform/stage is used
        type: string
        required: false
      terraform-root-prod:
        description: Root directory of terraform prod. When omitted, terraform/prod is used
        type: string
        required: false
    secrets:
      ORG_READ_ONLY_SSH_KEY:
        required: true
      ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN:
        required: true

jobs:
  ValidatePlanDev:
    name: TF Validate/Plan Dev
    uses: ./.github/workflows/tf_validate_plan_single_root.yml
    with:
      environment: dev
      commit-identifier: ${{ inputs.commit-identifier || github.sha }}
      oidc_domain: ${{ inputs.oidc_domain }}
      with-lock: false
      terraform-workspace: ${{ inputs.terraform-workspace || 'dev' }}
      terraform-root: ${{ inputs.terraform-root-dev || 'terraform/dev' }}
      terraform-version: ${{ inputs.terraform-version }}
    secrets:
      ORG_READ_ONLY_SSH_KEY: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}
      ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN: ${{ secrets.ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN }}

  ValidatePlanStage:
    name: TF Validate/Plan Stage
    uses: ./.github/workflows/tf_validate_plan_single_root.yml
    with:
      environment: stage
      commit-identifier: ${{ inputs.commit-identifier || github.sha }}
      oidc_domain: ${{ inputs.oidc_domain }}
      with-lock: false
      terraform-workspace: ${{ inputs.terraform-workspace || 'stage' }}
      terraform-root: ${{ inputs.terraform-root-stage || 'terraform/stage' }}
      terraform-version: ${{ inputs.terraform-version }}
    secrets:
      ORG_READ_ONLY_SSH_KEY: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}
      ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN: ${{ secrets.ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN }}
    
  ValidatePlanProd:
    name: TF Validate/Plan Prod
    uses: ./.github/workflows/tf_validate_plan_single_root.yml
    with:
      environment: prod
      commit-identifier: ${{ inputs.commit-identifier || github.sha }}
      oidc_domain: ${{ inputs.oidc_domain }}
      with-lock: false
      terraform-workspace: ${{ inputs.terraform-workspace || 'prod' }}
      terraform-root: ${{ inputs.terraform-root-prod || 'terraform/prod' }}
      terraform-version: ${{ inputs.terraform-version }}
    secrets:
      ORG_READ_ONLY_SSH_KEY: ${{ secrets.ORG_READ_ONLY_SSH_KEY }}
      ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN: ${{ secrets.ORG_GITHUB_PACKAGES_READ_ONLY_TOKEN }}
